server.port: 9036
spring:
  application:
    name: onair-hot-article-service
  data:
    redis:
      host: 127.0.0.1
      port: 6433
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: onair-hot-article-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
endpoints:
  onair-article-service:
    url: http://127.0.0.1:9030