server:
  port: 9038
spring:
  application:
    name: onair-article-images-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/article_images
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      s3:
        path-style-access-enabled: true
      credentials:
        access-key: ${AMAZON_S3_ACCESS_KEY}
        secret-key: ${AMAZON_S3_SECRET_KEY}
      region:
        static: ap-northeast-2
bucket:
  name: onairmarket
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method