server:
  port: 9032
spring:
  cloud:
    gateway:
      routes:
        - id: onair-article-service
          uri: http://localhost:9030
          predicates:
            - Path=/v1/article/**

        - id: onair-member-service
          uri: http://localhost:9031
          predicates:
            - Path=/v1/member/**

        - id: onair-comment-service
          uri: http://localhost:9033
          predicates:
            - Path=/v1/comment/**

        - id: onair-like-service
          uri: http://localhost:9034
          predicates:
            - Path=/v1/article-like/**

        - id: onair-view-service
          uri: http://localhost:9035
          predicates:
            - Path=/v1/article-views/**

        - id: onair-hot-article-service
          uri: http://localhost:9036
          predicates:
            - Path=/v1/hot-articles/**

        - id: onair-article-summary-service
          uri: http://localhost:9037
          predicates:
            - Path=/v1/article-summary/**

        - id: onair-article-images-service
          uri: http://localhost:9038
          predicates:
            - Path=/v1/article-images/**